name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]
    paths: ['platform/**']

jobs:
  CLAAssistant:
    if: github.repository == 'plasmicapp/plasmic'
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # the below token should have repo scope and must be manually added by you in the repository's secret
        with:
          path-to-signatures: '.github/cla-signatures.json'
          path-to-document: 'https://github.com/plasmicapp/plasmic/blob/master/docs/contributing/individual-cla.md' # e.g. a CLA or a DCO document
          # branch should not be protected
          branch: 'master'
#          allowlist: user1,bot*

         # the followings are the optional inputs - If the optional inputs are not given, then default values will be taken
          #remote-organization-name: enter the remote organization name where the signatures should be stored (Default is storing the signatures in the same repository)
          #remote-repository-name: enter the  remote repository name where the signatures should be stored (Default is storing the signatures in the same repository)
          #create-file-commit-message: 'For example: Creating file for storing CLA Signatures'
          #signed-commit-message: 'For example: $contributorName has signed the CLA in $owner/$repo#$pullRequestNo'
          custom-notsigned-prcomment: '<br/><br/>Thank you for your submission, we really appreciate it! ❤️ Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/plasmicapp/plasmic/blob/master/docs/contributing/individual-cla.md) before we can accept your contribution.<br/><br/>You can sign the CLA by just posting a Pull Request Comment, the same as the text below.<br/><br/>If you are contributing on behalf of a company, please have your company contact us to sign a [Corporate Contributor License Agreement](https://github.com/plasmicapp/plasmic/blob/master/docs/contributing/corporate-cla.md), via community@plasmic.app.'
          #custom-pr-sign-comment: 'The signature to be committed in order to sign the CLA'
          #custom-allsigned-prcomment: 'pull request comment when all contributors has signed, defaults to **CLA Assistant Lite bot** All Contributors have signed the CLA.'
          #lock-pullrequest-aftermerge: false - if you don't want this bot to automatically lock the pull request after merging (default - true)
          #use-dco-flag: true - If you are using DCO instead of CLA
